### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by fommil** [typesafehub/sbt-tojar#1]
when I ran this on Windows 7 / scala 2.10.4, with a completely clean `target` directory, I got a compiler exception (with a "last tree to typer" dump) and this

```
[error] uncaught exception during compilation: java.io.FileNotFoundException
```

most notably, the jar file was created as a directory! Is there perhaps some bug in the compiler's output of the jar?

**Comment by fommil** [comment]
@sethtisue

**Comment by fommil** [comment]
oh hold on, I'm not using RC2 (and we can't upgrade). Can you let me know the exact diffs to apply to 0.13.9 to get the required features?

**Comment by eed3si9n** [comment]
https://github.com/cunei/sbt/commit/3e50fdc825837f4dc10be1657af135387168e810

**Comment by fommil** [comment]
@eed3si9n sweet! I thought it would be a simple one liner like that. bloody directories :smile:
