### ISSUE TITLE
javac returned nonzero exit code

### ISSUE THREAD

**Issue by fommil** [typesafehub/sbt-tojar#2]
I'm testing this on a mixed source project and I get this

```
javac returned nonzero exit code
```

although the jar is produced (much faster than going to class directories, especially on full recompiles)

**Comment by eed3si9n** [comment]
Since compiling straight to JAR is a scalac feature, we probably need special handling when you have `*.java` in the mix.

**Comment by cunei** [comment]
The restriction is mentioned on the project page: at this time scala-only subprojects can compile directly to jar. The main issue is that the internals of sbt use shared structures to describe where the classfiles should be created; if the target is a jar file (which is correctly interpreted by scalac), then javac won't be able to create its own classes. I am now looking into alternative tweaks that may be used to convince scalac and javac to create their files into two different destinations, inserting the classes generated by javac into the jar post-facto. All that may be possible from an sbt plugin, but we might also need some deeper refactoring of the related code within sbt; I am now investigating how that can be made to work.

**Comment by cunei** [comment]
Mixed Java/Scala projects should work starting with d9e96695079190dea67b08b1e2edbac636df973a, please let us know if that works with your code.
